blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/ishandutta2007/beautiful-github-homepage/discussions
    about: Please ask and answer questions here.
  - name: Error
    url: https://github.com/ishandutta2007/beautiful-github-homepage/issues/1772
    about:
      Before opening a bug report, please check the 'Common Error Codes' issue.
  - name: FAQ
    url: https://github.com/ishandutta2007/beautiful-github-homepage/discussions/1770
    about: Please first check the FAQ before asking a question.
