name: Deployment Prep
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  config:
    if: github.repository == 'ishandutta2007/beautiful-github-homepage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Deployment Prep
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
