name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  triage:
    if: github.repository == 'ishandutta2007/beautiful-github-homepage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
